stages:
 - pre-deploy
 - deploy-staging
 - deploy-production


pre-deploy:
 stage: pre-deploy
 script:
    - echo "---Pre-Deploy---"
 environment:
    name: staging
 tags:
    - sam

staging-runner:
 stage: deploy-staging
 script:
    - bash deploy.sh staging
 environment:
    name: staging
 when: manual
 tags:
    - sam
    

    
production-runner:
 stage: deploy-production
 script:
   - bash deploy.sh prod
 environment:
   name: production
 rules:
   - if: $CI_COMMIT_TAG != null
     when: manual
 tags:
   - sam
